import React from 'react';
import { useData } from '../../context/DataContext';
import { Card, CardHeader, CardBody } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Alert } from '../../components/ui/Alert';
import { generateCivicIntelligenceInsights } from '../../services/bedrockService';
import {
  BarChart3,
  TrendingUp,
  PieChart,
  Clock,
  Layers,
  Cpu,
  MapPin,
  CheckCircle2,
  AlertTriangle
} from 'lucide-react';

export const AnalyticsPage: React.FC = () => {
  const { issues, incidents } = useData();

  const aiInsights = generateCivicIntelligenceInsights(issues, incidents);

  // Category Distribution
  const categoryCounts: Record<string, number> = {};
  issues.forEach((i) => {
    categoryCounts[i.category] = (categoryCounts[i.category] || 0) + 1;
  });

  // Status Distribution
  const statusCounts: Record<string, number> = {};
  incidents.forEach((inc) => {
    statusCounts[inc.status] = (statusCounts[inc.status] || 0) + 1;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-civic-navy tracking-tight">Civic Intelligence Analytics</h1>
          <p className="text-xs sm:text-sm text-slate-600 mt-0.5">
            Aggregated trends, incident clustering velocity, category distribution, and Bedrock AI insights.
          </p>
        </div>
      </div>

      {/* AI Intelligence Insights Disclaimer Banner */}
      <Alert variant="info" title="AI-Generated Predictive Insights Notice">
        The analytics insights below are predictive predictions generated by Amazon Bedrock AI using spatial-temporal pattern models. AI-generated insights are probabilistic and should be evaluated alongside official municipal inspections.
      </Alert>

      {/* AI Insights Card */}
      <Card className="border-2 border-indigo-200 bg-indigo-50/40">
        <CardHeader className="bg-indigo-100/70">
          <h3 className="font-bold text-xs uppercase tracking-wider text-indigo-950 flex items-center gap-2">
            <Cpu className="w-4 h-4 text-indigo-700" />
            AI-Generated Trend & Pattern Predictions
          </h3>
        </CardHeader>
        <CardBody className="p-5 grid grid-cols-1 md:grid-cols-2 gap-4">
          {aiInsights.map((insight, idx) => (
            <div key={idx} className="p-3 bg-white border border-indigo-200 rounded-lg shadow-2xs space-y-1">
              <span className="text-[10px] font-bold text-indigo-700 uppercase tracking-wider block">
                Insight Pattern #{idx + 1}
              </span>
              <p className="text-xs font-semibold text-civic-navy leading-relaxed">{insight}</p>
              <span className="text-[10px] text-slate-400 block pt-1">Model: Bedrock Claude 3 Haiku • Confidence: High</span>
            </div>
          ))}
        </CardBody>
      </Card>

      {/* Analytics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Category Breakdown */}
        <Card>
          <CardHeader>
            <h3 className="font-bold text-sm text-civic-navy flex items-center gap-2">
              <PieChart className="w-4 h-4 text-civic-accent" />
              Citizen Reports by Category
            </h3>
          </CardHeader>
          <CardBody className="p-5 space-y-4">
            {Object.entries(categoryCounts).map(([cat, count]) => {
              const percent = Math.round((count / issues.length) * 100);
              return (
                <div key={cat} className="space-y-1 text-xs">
                  <div className="flex justify-between font-bold text-civic-navy">
                    <span>{cat}</span>
                    <span>{count} reports ({percent}%)</span>
                  </div>
                  <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div className="h-full bg-civic-accent rounded-full" style={{ width: `${percent}%` }} />
                  </div>
                </div>
              );
            })}
          </CardBody>
        </Card>

        {/* Incident Status Distribution */}
        <Card>
          <CardHeader>
            <h3 className="font-bold text-sm text-civic-navy flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-civic-accent" />
              Civic Incident Status Lifecycle
            </h3>
          </CardHeader>
          <CardBody className="p-5 space-y-4">
            {Object.entries(statusCounts).map(([status, count]) => {
              const percent = Math.round((count / incidents.length) * 100);
              return (
                <div key={status} className="space-y-1 text-xs">
                  <div className="flex justify-between font-bold text-civic-navy">
                    <span>{status.replace('_', ' ')}</span>
                    <span>{count} incidents ({percent}%)</span>
                  </div>
                  <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                    <div
                      className={`h-full rounded-full ${
                        status === 'RESOLVED' ? 'bg-emerald-500' : status === 'ASSIGNED' ? 'bg-blue-600' : 'bg-amber-500'
                      }`}
                      style={{ width: `${percent}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </CardBody>
        </Card>

        {/* Resolution Velocity Metric */}
        <Card>
          <CardHeader>
            <h3 className="font-bold text-sm text-civic-navy flex items-center gap-2">
              <Clock className="w-4 h-4 text-civic-accent" />
              Average Resolution Velocity by Category
            </h3>
          </CardHeader>
          <CardBody className="p-5 space-y-3 text-xs">
            <div className="p-3 bg-slate-50 border rounded-md flex justify-between items-center">
              <span className="font-bold text-civic-navy">Road Infrastructure</span>
              <span className="font-bold text-emerald-700">4.2 Hours Avg</span>
            </div>
            <div className="p-3 bg-slate-50 border rounded-md flex justify-between items-center">
              <span className="font-bold text-civic-navy">Water & Sewerage</span>
              <span className="font-bold text-emerald-700">2.8 Hours Avg (High Priority)</span>
            </div>
            <div className="p-3 bg-slate-50 border rounded-md flex justify-between items-center">
              <span className="font-bold text-civic-navy">Electricity & Lighting</span>
              <span className="font-bold text-emerald-700">6.1 Hours Avg</span>
            </div>
          </CardBody>
        </Card>

        {/* Hotspots Concentration Card */}
        <Card>
          <CardHeader>
            <h3 className="font-bold text-sm text-civic-navy flex items-center gap-2">
              <MapPin className="w-4 h-4 text-civic-accent" />
              Highest Concentration Hotspot Zones
            </h3>
          </CardHeader>
          <CardBody className="p-5 space-y-3 text-xs">
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-md space-y-1">
              <div className="flex justify-between font-bold text-amber-950">
                <span>Zone 1: Main St & 4th Ave Intersection</span>
                <span>3 Related Reports</span>
              </div>
              <p className="text-[11px] text-amber-900">
                Primary Issue: Severe Road Potholes & Rim Damage. Grouped under Incident #42.
              </p>
            </div>

            <div className="p-3 bg-blue-50 border border-blue-200 rounded-md space-y-1">
              <div className="flex justify-between font-bold text-blue-950">
                <span>Zone 3: Elm St Residential Block</span>
                <span>2 Related Reports</span>
              </div>
              <p className="text-[11px] text-blue-900">
                Primary Issue: Water Pipe Burst & Standing Water. Grouped under Incident #43.
              </p>
            </div>
          </CardBody>
        </Card>
      </div>
    </div>
  );
};
